---
version: "3.4"
services:
  db:
    container_name: postgres
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      cache_from:
        - us.gcr.io/kubernetes-dev/vectorapi:latest
    volumes:
      - ./vectorapi:/app/vectorapi
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./docs:/app/docs
      - ./.sentence_transformers:/app/.sentence_transformers
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      VECTORAPI_STORE_SCHEMA: vector
      PORT: 8889
    ports:
      - 8889:8889
    depends_on:
      - db
