---
version: "3.4"
services:
  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
      PORT: 8889
    ports:
      - 8889:8889
    depends_on:
      - postgres